// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jirokun/go_frameworks/chi/handler"
	"github.com/jirokun/go_frameworks/chi/infra"
	"github.com/jirokun/go_frameworks/chi/usecase"
)

// Injectors from wire.go:

func InitializeServerInterface() *handler.ServerInterfaceImpl {
	petRepository := infra.NewPetRepositoryImpl()
	petUsecase := usecase.NewPetUsecase(petRepository)
	serverInterfaceImpl := handler.NewServerInterfaceImpl(petUsecase)
	return serverInterfaceImpl
}
